syntax = "proto3";

option csharp_namespace = "Veritas.PlatformService.Contracts.Grpc";

package veritas.platform.v1;

import "google/protobuf/empty.proto";

service PlatformSetup {
  rpc GetSetupStatus(google.protobuf.Empty) returns (GetSetupStatusResponse);
  rpc CompleteSetup(CompleteSetupRequest) returns (CompleteSetupResponse);
}

message GetSetupStatusResponse {
  bool is_setup_completed = 1;
}

message CompleteSetupRequest {
  AdminUser admin_user = 1;
}

message CompleteSetupResponse {
  bool is_setup_completed = 1;
}

message AdminUser {
  string email = 1;
  string password = 2;
}
