// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Veritas.MessagingService.Infrastructure.Database;

#nullable disable

namespace Veritas.MessagingService.Infrastructure.Database.Migrations
{
    [DbContext(typeof(MessagingDbContext))]
    partial class MessagingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("messaging")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Veritas.MessagingService.Domain.Entities.EmailTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TextBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "TemplateKey")
                        .IsUnique();

                    b.ToTable("email_templates", "messaging");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ad2403c4-e51c-44f8-87c5-a8ead8818065"),
                            CreatedAtUtc = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            HtmlBody = "<p>Welcome {{User.DisplayName}}.</p><p>Open Veritas: {{Action.Url}}</p>",
                            IsEnabled = true,
                            Subject = "Welcome to Veritas, {{User.Email}}",
                            TemplateKey = "admin.welcome",
                            TextBody = "Welcome {{User.DisplayName}}. Open Veritas: {{Action.Url}}",
                            UpdatedAtUtc = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("7f069c98-2a31-4e53-a3b2-383e24274f8c"),
                            CreatedAtUtc = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            HtmlBody = "<p>SMTP test for {{System.InstanceName}} at {{System.TimestampUtc}}</p>",
                            IsEnabled = true,
                            Subject = "Veritas SMTP test",
                            TemplateKey = "system.smtp-test",
                            TextBody = "SMTP test for {{System.InstanceName}} at {{System.TimestampUtc}}",
                            UpdatedAtUtc = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Veritas.MessagingService.Domain.Entities.SmtpSettings", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FromName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsConfigured")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSuccessfulTestAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("ProtectedSecret")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("TlsMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("smtp_settings", "messaging");
                });
#pragma warning restore 612, 618
        }
    }
}
