/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as BootstrapRouteImport } from './routes/_bootstrap'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AdminBootstrapSmtpRouteImport } from './routes/_admin/bootstrap/smtp'
import { Route as BootstrapBootstrapCompleteRouteImport } from './routes/_bootstrap/bootstrap/complete'
import { Route as BootstrapBootstrapStartRouteImport } from './routes/_bootstrap/bootstrap/start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BootstrapRoute = BootstrapRouteImport.update({
  id: '/_bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const AdminBootstrapSmtpRoute = AdminBootstrapSmtpRouteImport.update({
  id: '/bootstrap/smtp',
  path: '/bootstrap/smtp',
  getParentRoute: () => AdminRoute,
} as any)
const BootstrapBootstrapCompleteRoute =
  BootstrapBootstrapCompleteRouteImport.update({
    id: '/bootstrap/complete',
    path: '/bootstrap/complete',
    getParentRoute: () => BootstrapRoute,
  } as any)
const BootstrapBootstrapStartRoute = BootstrapBootstrapStartRouteImport.update({
  id: '/bootstrap/start',
  path: '/bootstrap/start',
  getParentRoute: () => BootstrapRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AdminDashboardRoute
  '/login': typeof GuestLoginRoute
  '/bootstrap/smtp': typeof AdminBootstrapSmtpRoute
  '/bootstrap/complete': typeof BootstrapBootstrapCompleteRoute
  '/bootstrap/start': typeof BootstrapBootstrapStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AdminDashboardRoute
  '/login': typeof GuestLoginRoute
  '/bootstrap/smtp': typeof AdminBootstrapSmtpRoute
  '/bootstrap/complete': typeof BootstrapBootstrapCompleteRoute
  '/bootstrap/start': typeof BootstrapBootstrapStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_bootstrap': typeof BootstrapRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_admin/bootstrap/smtp': typeof AdminBootstrapSmtpRoute
  '/_bootstrap/bootstrap/complete': typeof BootstrapBootstrapCompleteRoute
  '/_bootstrap/bootstrap/start': typeof BootstrapBootstrapStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/bootstrap/smtp'
    | '/bootstrap/complete'
    | '/bootstrap/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/bootstrap/smtp'
    | '/bootstrap/complete'
    | '/bootstrap/start'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_bootstrap'
    | '/_guest'
    | '/_admin/dashboard'
    | '/_guest/login'
    | '/_admin/bootstrap/smtp'
    | '/_bootstrap/bootstrap/complete'
    | '/_bootstrap/bootstrap/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BootstrapRoute: typeof BootstrapRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_bootstrap': {
      id: '/_bootstrap'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_admin/bootstrap/smtp': {
      id: '/_admin/bootstrap/smtp'
      path: '/bootstrap/smtp'
      fullPath: '/bootstrap/smtp'
      preLoaderRoute: typeof AdminBootstrapSmtpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_bootstrap/bootstrap/complete': {
      id: '/_bootstrap/bootstrap/complete'
      path: '/bootstrap/complete'
      fullPath: '/bootstrap/complete'
      preLoaderRoute: typeof BootstrapBootstrapCompleteRouteImport
      parentRoute: typeof BootstrapRoute
    }
    '/_bootstrap/bootstrap/start': {
      id: '/_bootstrap/bootstrap/start'
      path: '/bootstrap/start'
      fullPath: '/bootstrap/start'
      preLoaderRoute: typeof BootstrapBootstrapStartRouteImport
      parentRoute: typeof BootstrapRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminBootstrapSmtpRoute: typeof AdminBootstrapSmtpRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminBootstrapSmtpRoute: AdminBootstrapSmtpRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BootstrapRouteChildren {
  BootstrapBootstrapCompleteRoute: typeof BootstrapBootstrapCompleteRoute
  BootstrapBootstrapStartRoute: typeof BootstrapBootstrapStartRoute
}

const BootstrapRouteChildren: BootstrapRouteChildren = {
  BootstrapBootstrapCompleteRoute: BootstrapBootstrapCompleteRoute,
  BootstrapBootstrapStartRoute: BootstrapBootstrapStartRoute,
}

const BootstrapRouteWithChildren = BootstrapRoute._addFileChildren(
  BootstrapRouteChildren,
)

interface GuestRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BootstrapRoute: BootstrapRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
